In [1]:
import numpy as np

In [2]:
a = np.array([[3,1], [1,2]])

In [3]:
b = np.array([9,8])

In [4]:
x = np.linalg.solve(a, b)

In [5]:
x

array([2., 3.])

In [6]:
np.allclose(np.dot(a, x), b)

True

In [7]:
 x = np.arange(9)

In [8]:
x = x.reshape(3, 3)

In [19]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
y= np.roll(x, 1, axis=0)

In [20]:
print(y)

[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [18]:
diff = np.absolute(x-y)
diff

array([[6, 6, 6],
       [3, 3, 3],
       [3, 3, 3]])

In [21]:
print(diff.mean())

4.0


In [22]:
diff.mean(0)

array([4., 4., 4.])

In [23]:
diff.mean(1)

array([6., 3., 3.])